version: '2'

services:
  webserver:
    build: ./docker-prod
    image: test
    ports:
      - "8800:80"
      - "443:443"
    volumes:
      - ./production-root/:/var/www/
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "4407:3306"
    volumes:
      - ./production-root/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_runwaytest