version: '2'

services:
  webserver:
    build: ./docker-dev
    environment:
        XDEBUG_CONFIG: remote_host=172.18.0.1
        PHP_IDE_CONFIG: "serverName=Docker-dev"
        PHP_DEV_PROD: "development"
        #XDEBUG_CONFIG: remote_enable=on
        #XDEBUG_CONFIG: remote_autostart=on

    image: test
    ports:
      - "8800:80"
      - "443:443"
    volumes:
      - /var/www/html/webforge-test/:/var/www/
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "4407:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_runwaytest