version: '2'

services:
  webserver:
    build: ./docker-dev
    environment:
        XDEBUG_CONFIG: remote_host=172.18.0.1
        PHP_IDE_CONFIG: "serverName=Docker-dev"
        PHP_DEV_PROD: "development"
        #XDEBUG_CONFIG: remote_enable=on
        #XDEBUG_CONFIG: remote_autostart=on

    image: test
    ports:
      - "8800:80"
      - "443:443"
    volumes:
      - /var/www/html/webforge-test/:/var/www/
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "4407:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      #- MYSQL_ROOT_PASSWORD=oj7hoincdlknIGGUSh4237nkd97HJBcgdhTDcz
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webforge
     # - MYSQL_USER=webforgeuser
     # - MYSQL_PASSWORD=0ny7GTGYSGV7534POIQImx9JHDSFGggcf26UYyhsg67
      - MYSQL_ROOT_HOST=172.18.0.1
     #- MYSQL_ALLOW_EMPTY_PASSWORD=yes